name: prowtech
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.8
#   http: ^1.2.2
#   # shared_preferences: ^2.0.15
#   video_player: ^2.4.4
#   flutter_video_player: ^2.1.0
#   chewie: ^1.3.4

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/logo.png
#     - assets/videos/afa3256016ebc1e1c74d.mp4
#     - assets/images/03c78e1fb5cca1e01a30.png

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  video_player: ^2.4.4
  chewie: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/03c78e1fb5cca1e01a30.png
    - assets/videos/
